version: '3.8'

services:
  profile-webapp:
    container_name: docker-pwa-profile
    image: docker-pwa-profile-i
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/ssl